TeachCourses/TeachCourses/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('lessons.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TeachCourses/lessons/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView, name='index'),
    path('lessons/', views.LessonsView, name='lessons'),
    path('homework/', views.HomeWorkView, name='homework'),
    path('logout/', views.LogoutView, name='logout'),
    path('register/', views.RegisterView, name='register'),
    path('login/', views.LoginView, name='login'),
    path('changepw/', views.ChangePasswordView, name='changepw'),
    path('forgotpw/', views.ForgotPasswordView, name='forgotpw'),
]

TeachCourses/lessons/models.py
from django.db import models
from django.contrib.auth.models import User

class Announcement(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=256, default='Blank')
    content = models.CharField(max_length=1024)
    pub_date = models.DateTimeField('date_published', null=True)

    def __str__(self):
        return self.author.username + ':' + self.title

class Category(models.Model):
    name = models.CharField(max_length=256)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Lesson(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    content = models.FileField(upload_to='files')

    def __str__(self):
        return self.category.name + ":" + self.name

class HomeWork(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    content = models.FileField(upload_to='files')

    def __str__(self):
        return self.category.name + ":" + self.name

class Token(models.Model):
    value = models.CharField(max_length=256)

    def __str__(self):
        return 'Token:' + self.value

TeachCourses/lessons/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404
from django.contrib import messages
from .security import check_email, get_random_password, get_user
from django.core.mail import send_mail

def IndexView(request):
    announcements = models.Announcement.objects.order_by('-pub_date')
    return render(request, 'lessons/index.htm', {'announcements': announcements})

def LessonsView(request):
    categories = models.Category.objects.all()
    return render(request, 'lessons/lessons.htm', {'categories': categories})

def HomeWorkView(request):
    categories = models.Category.objects.all()
    return render(request, 'lessons/homework.htm', {'categories': categories})

def LogoutView(request):
    logout(request)
    return redirect(reverse('index'))

def RegisterView(request):
    form = UserCreationForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            token = models.Token.objects.filter(value=request.POST['token'])
            if token:
                token = token[0]
            if token:
                user = form.save(commit=False)
                user.email = request.POST['email']
                if not check_email(request.POST['email']):
                    messages.error(request, "Email is not correct.")
                    return redirect(reverse('register'))
                user.save()
                token.delete()
                user = authenticate(username=form.cleaned_data.get("username"), password=form.cleaned_data.get("password1"))
                if user is not None:
                    login(request, user)
                else:
                    return Http404()
                return redirect(reverse('index'))
            else:
                messages.error(request, 'Token does not exist. Make sure that your token is correct and you own a token or contact with the teacher.')
                return redirect('.')
        else:
            return redirect('.')
    else:
        return render(request, 'lessons/register.htm', {'form': form})

def LoginView(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('index'))
        else:
            messages.error(request, "Username and password do not match.")
            return redirect(".")
    return render(request, 'lessons/login.htm')

def ChangePasswordView(request):
    if request.method == 'POST':
        username = request.user.username
        curpass = request.POST.get("curpass")
        user = authenticate(username=username, password=curpass)
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        if not password1 or not password2:
            messages.error(request, "New password can't be blank")
        if user is None:
            messages.error(request, "Current password is not valid.")
            return redirect(reverse('changepw'))
        if password1 != password2:
            messages.error(request, "Passwords do not match.")
            return redirect(reverse('changepw'))
        if len(password1) < 8:
            messages.error(request, "New password must me at least 8 characters long.")
            return redirect(reverse('changepw'))
        request.user.set_password(password1)
        request.user.save()
        user = authenticate(username=username, password=password1)
        login(request, user)
        messages.success(request, "Password changed successfully")
        return redirect(reverse('changepw'))
    return render(request, 'lessons/changepw.htm')

def ForgotPasswordView(request):
    if request.method == 'POST':
        email = request.POST.get("email")
        if not check_email(email):
            messages.error(request, "Email is not valid!")
            return redirect(reverse('forgotpw'))
        print(email)
        password = get_random_password(8)
        username = request.POST['username']
        user = get_user(username)
        user.set_password(password)
        user.save()    
        send_mail(
            'TeachingCourses:Forgot Password',
            'Hey there, your new password has successfully been set and it is: {}'.format(password),
            'meintsot01@gmail.com',
            [email],
            fail_silently=False,
        )
        messages.success(request, "A new password has been sent to your email. Use this password to log in and then go to Change password and set a new one.")
        return redirect(reverse('login'))
    return render(request, 'lessons/forgotpw.htm')

TeachCourses/lessons/templates/lessons/base.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock %}
</head>
<body>
    <link rel="stylesheet" href="{% static 'bootstrap4/dist/css/bootstrap.css' %}">
    <nav class="navbar navbar-expand-sm bg-dark">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{% url 'index' %}" class="nav-link h3 text-light mr-3">Home</a></li>
            <li class="nav-item"><a href="{% url 'lessons' %}" class="nav-link h3 text-light mr-3">Lessons</a></li>
            <li class="nav-item"><a href="{% url 'homework' %}" class="nav-link h3 text-light mr-3">Homework</a></li>
            <li class="nav-item"><a href="" class="nav-link h3 text-light mr-3">Forum</a></li>
            {% if user.is_active %}
            <li class="nav-item"><a href="" class="nav-link h3 text-light mr-3">Profile</a></li>
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link h3 text-light mr-3">Logout</a></li>
            <li class="nav-item"><a href="{% url 'changepw' %}" class="nav-link h3 text-light mr-3">Change Password</a></li>
            {% else %}
            <li class="nav-item"><a href="{% url 'login' %}" class="nav-link h3 text-light mr-3">Login</a></li>
            <li class="nav-item"><a href="{% url 'register' %}" class="nav-link h3 text-light mr-3">Register</a></li>
            {% endif %}
        </ul>
    </nav>
    {% block main %}{% endblock %}
</body>
</html>

TeachCourses/lessons/templates/lessons/changepw.htm
{% extends 'lessons/base.htm' %}

{% block title %}
<title>changepw</title>
{% endblock %}

{% block main %}
<form method="post">
    {% csrf_token %}
    <h2>Change your password here</h2>
    <label>Current password: </label>
    <input type="password" name="curpass"><br>
    <label>New password: </label>
    <input type="password" name="password1"><br>
    <label>New password(retype): </label>
    <input type="password" name="password2"><br>
    <input type="submit" value="Change Password">
    {% for message in messages %}
    <h3>{{ message }}</h3>
    {% endfor %}
</form>
{% endblock %}

TeachCourses/lessons/templates/lessons/forgotpw.htm
{% extends 'lessons/base.htm' %}

{% block title %}
<title>Forgot password</title>
{% endblock %}

{% block main %}
<form method="post">
    {% csrf_token %}
    <h3>Please enter the email address and your current username to send your new password:</h3>
    <label>Email: </label>
    <input type="email" name="email"><br>
    <label>Username: </label>
    <input type="text" name="username"><br>
    <input type="submit" value="send"><br>
    {% for message in messages %}
    <h3>{{ message }}</h3>
    {% endfor %}
</form>
{% endblock %}

TeachCourses/lessons/templates/lessons/homework.htm
{% extends 'lessons/base.htm' %}

{% block title %}
<title>Homework</title>
{% endblock %}

{% block main %}
    {% if user.is_authenticated %}
        {% if categories %}
            {% for category in categories %}
                <h1>{{ category.name }}</h1>
                {% for homework in category.homework_set.all %}
                <h3><a href="{{ category.file.url }}" download>{{ homework.name }}</a></h3>
                {% endfor %}
            {% endfor %}
        {% endif %}
    {% else %}
    You need to login
    {% endif %}
{% endblock %}

TeachCourses/lessons/templates/lessons/index.htm
{% extends 'lessons/base.htm' %}

{% block title %}
<title>Index</title>
{% endblock %}

{% block main %}
    {% if not announcements %}
    <h1>No announcements</h1>
    {% else %}
        {% for announcement in announcements %}
            <div>
                <h1>{{ announcement.title }}</h1>
                <p>{{ announcement.content }}</p>
                <div><i>{{ announcement.author.username }}</i></div>
            </div>
        {% endfor %}
        {% endif %}
{% endblock %}

TeachCourses/lessons/templates/lessons/lessons.htm
{% extends 'lessons/base.htm' %}

{% block title %}
<title>Lessons</title>
{% endblock %}

{% block main %}
    {% if user.is_authenticated %}
        {% for category in categories %}
            <h1>{{ category.name }}</h1>
            {% for lesson in category.lesson_set.all %}
            <h3><a href="{{ lesson.content.url }}" download>{{ lesson.name }}</a></h3>
            {% endfor %}
        {% endfor %}
    {% else %}
    You need to login to access the lessons
    {% endif %}
{% endblock %}

TeachCourses/lessons/templates/lessons/login.htm
{% extends 'lessons/base.htm' %}

{% block title %}
<title>Login</title>
{% endblock %}

{% block main %}
<form method="post">
    {% csrf_token %}
    <h1>Login</h1>
    <label>Username: </label>
    <input type="text" name="username"><br>
    <label>Password: </label>
    <input type="password" name="password"><br>
    <input type="submit" value="Login">
    {% for message in messages %}
    <h3>{{ message }}</h3>
    {% endfor %}
</form>
<a href="{% url 'forgotpw' %}">Forgot your password? Click here</a>
{% endblock %}

TeachCourses/lessons/templates/lessons/register.htm
{% extends 'lessons/base.htm' %}

{% block title %}
<title>Register</title>
{% endblock %}

{% block main %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }} <br>
    <label>Email: </label>
    <input type="email" name="email"><br>
    <label>Token: </label>
    <input type="text" name="token"><br>
    <input type="submit" value="Register">
    {% if messages %}
        {% for message in messages %}
        <h2>{{ message }}</h2>
        {% endfor %}
    {% endif %}
</form>
{% endblock %}